<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_CPUStats" Id="{4924dc9b-8b6c-4a75-b137-0d73fc714c13}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CPUStats
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    fbCpuStats : FB_IPCDiag_ReadParameter;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>